
# Describe valid chars (Mozilla DeepSpeech format).
# More information you can find in the `text.Alphabet` class.

alphabet:
  file_path: data/polish-alphabet.txt


# Custom architecture can be added to the file `model.py`.
# Define the model name and pass parameters.

model:
  name: deepspeech-ctc
  fc_sizes: [64]
  rnn_sizes: [64, 128, 256, 512, 1024]
  output_dim: 36
  random_seed: 123
  stddev: 0.05


# The available optimizers are specified in: `deepspeech.__get_optimizer` and
# come from `keras.optimizers` module. You can use keras documentation to get
# more information and overwrite default parameters (use the same names).

optimizer:
  name: adam
  lr: 0.001
  beta_1: 0.9
  beta_2: 0.999
  epsilon: 0.00000001


# Define callbacks to get a view on internal states and statistics of the model
# during training.

callbacks:
- name: TerminateOnNaN

- name: CustomModelCheckpoint
  log_dir: checkpoints

- name: CustomTensorBoard
  log_dir: tensorboard

- name: LearningRateScheduler
  # Around 8% at epoch 25
  k: 0.1
  verbose: 1

- name: CustomEarlyStopping
  mini_targets:
    5: 200
    10: 100
  monitor: val_loss
  patience: 3
